title: Jonathan Davidson
description: Personal Website for Jonathan Davidson
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

search_enabled: true
color_scheme: light

markdown: kramdown

collections:
  notes:
    output: true
    permalink: /notes/:path/
  teaching:
    output: true
    permalink: /teaching/:path/
  research:
    output: true
    permalink: /research/:path/

just_the_docs:
  collections:
    notes:
      name: Notes
      nav_fold: true
    teaching:
      name: Teaching
      nav_fold: true
    research:
      name: Research
      nav_fold: true
